image: mcr.microsoft.com/playwright:v1.54.0-noble

pipelines:
  default:
    - step:
        name: Run Playwright Tests
        script:
          - npm ci
          - npx playwright install --with-deps
          - npx playwright test
        artifacts:
          - playwright-report/**
