image: node:20

pipelines:
  branches:
    staging:
      - step:
          name: Run Cloudemy Smoke Tests (Staging)
          caches:
            - node
          script:
            - npm ci
            - npx playwright install --with-deps
            - npx playwright test --grep "@smoke"
          artifacts:
            - playwright-report/**

    main:
      - step:
          name: Run Cloudemy Full Regression (Production)
          caches:
            - node
          script:
            - npm ci
            - npx playwright install --with-deps
            - npx playwright test
          artifacts:
            - playwright-report/**