image: mcr.microsoft.com/playwright:v1.44.0-jammy

pipelines:
  default:
    - step:
        name: Run Playwright Tests
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps
          - npx playwright test
