function genFormName(tag = 'DOM') {
  return `AUTO_${tag}_${Date.now().toString().slice(-6)}`;
}

module.exports = {
  formTemplate: {
    domestic: {
      formName: genFormName('DOM'),
      description: 'Automated domestic enrolment form',
      enrolmentInstruction: 'Please complete all required domestic enrolment details.',
      logo:'logo.png'
    }
  },
   
  customFieldConfig:{
    text: 'Test Text',
    email: 'test@example.com',
    number: '12345',
    textarea: 'This is a test textarea value generated by automation.',
    date: '01-01-2025',

    dropdown: {
      by: 'index', // index | value | label
      value: 1
    },

    radio: {
      index: 0
    },

    checkbox: {
      index: 0
    },

    file: 'photo.png'
  }
};
